name: CI

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v1
    - name: pygame-wasm-builder prepare
      run: |
            pwd
            echo
            python3 -V
            echo
            clang --version | head -n 1
            echo
            gcc --version | head -n 1
            echo
            env|grep GITHUB
            echo
            env|grep ANDROID
            echo
            sudo apt-get update 2>&1 >/dev/null
            sudo apt-get install -y bash wget lz4 pv  2>&1 >/dev/null

    - name: get pygame-wasm-plus
      run: |
            cd $GITHUB_WORKSPACE
            git clone --depth 1 --single-branch --branch main https://github.com/pygame-web/pygame-wasm-plus
            mv -vf pygame-wasm-plus/* ./


    - name: build 3.10
      run: |
            cd $GITHUB_WORKSPACE
            BUILDS=3.10 bash ./wasm-build-all.sh
            du -hs dist/*

    - name: build 3.11
      run: |
            cd $GITHUB_WORKSPACE
            BUILDS=3.11 bash ./wasm-build-all.sh
            du -hs dist/*

    - name: build 3.12
      run: |
            cd $GITHUB_WORKSPACE
            BUILDS=3.12 bash ./wasm-build-all.sh
            du -hs dist/*

           
    - name: publishing
      run: |
            cd $GITHUB_WORKSPACE
            du -hs $(find prebuilt/emsdk/)
            cp -fv static/* support/pythonrc.py dist/
           

    - name : "Upload to GitHub pages"
      uses: JamesIves/github-pages-deploy-action@4.1.7
      with:
        branch: gh-pages
        folder: dist

