name: CI

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-22.04
    env:
        SDK_VERSION: 0.6.0
        SYS_PYTHON: /usr/bin/python3

    steps:
    - uses: actions/checkout@v1
    - name: pygame-wasm-builder prepare
      run: |
            pwd
            echo
            python3 -V
            echo
            clang --version | head -n 1
            echo
            gcc --version | head -n 1
            echo
            env|grep GITHUB
            echo
            env|grep ANDROID
            echo
            sudo apt-get update 2>&1 >/dev/null
            sudo apt-get install -y bash git curl wget lz4 pv 2>&1 >/dev/null


    - name: build 3.10 packages
      run: |
            cd $GITHUB_WORKSPACE
            PYBUILD=3.10 bash ./scripts/build-pkg.sh

    - name: build 3.10 loader
      run: |
            cd $GITHUB_WORKSPACE
            PYBUILD=3.10 bash ./scripts/build-loader.sh
            du -hs dist/*






    - name: build 3.11 packages
      run: |
            cd $GITHUB_WORKSPACE
            PYBUILD=3.11 bash ./scripts/build-pkg.sh


    - name: build 3.11 loader
      run: |
            cd $GITHUB_WORKSPACE
            PYBUILD=3.11 bash ./scripts/build-loader.sh
            du -hs dist/*






    - name: build 3.12 packages
      run: |
            cd $GITHUB_WORKSPACE
            PYBUILD=3.12 bash ./scripts/build-pkg.sh


    - name: build 3.12 loader
      run: |
            cd $GITHUB_WORKSPACE
            PYBUILD=3.12 bash ./scripts/build-loader.sh
            du -hs dist/*



    - name: publishing
      run: |
            cd $GITHUB_WORKSPACE
            du -hs $(find vm/prebuilt/emsdk/)
            mv vm/dist ./
            cp -vf support/pythonrc.py dist/
            cp -rfv static/* dist/

    - name : "Upload to GitHub pages"
      uses: JamesIves/github-pages-deploy-action@4.1.7
      with:
        branch: gh-pages
        folder: dist

